
## TERMINAL SETTINGS
APPLICATION_NAME = "Auto Navigator v.0.1"

TERMINAL_WIDTH = 1000
TERMINAL_HEIGHT = 580

HIDDEN_WIDTH = 600
HIDDEN_HEIGHT = 100


## SEQUENCE PATH -> STORE AND LOAD SETUPS
SEQUENCE_PATH = './sequences/'


## AUTOINCREMENTAL NUMBER FILE PATH
AUTOINCREMENTAL_PATH = './components/autoincremental_value.txt'


## DEPENDENCIES !!! DO NOT MODIFY IN ANY CASE !!!
actions = []
running = True
