
## TERMINAL SETTINGS
APPLICATION_NAME = "Auto Navigator v.0.1"

TERMINAL_WIDTH = 1000
TERMINAL_HEIGHT = 300

HIDDEN_WIDTH = 500
HIDDEN_HEIGHT = 100


## SEQUENCE PATH -> STORE AND LOAD SETUPS
SEQUENCE_PATH = './sequences/'
