
## TERMINAL SETTINGS
APPLICATION_NAME = "AutoExec Suite v1.0"

TERMINAL_WIDTH = 1000
TERMINAL_SMALL_HEIGHT = 300
TERMINAL_MEDIUM_HEIGHT = 500
TERMINAL_TALL_HEIGHT = 640

HIDDEN_WIDTH = 600
HIDDEN_HEIGHT = 100


## SEQUENCE PATH -> STORE AND LOAD SETUPS
SEQUENCE_PATH = './sequences/'

## OUTPUT COMMAND PATH -> SAVE OUTPUT FILES
OUTPUT_COMMANDS_PATH = './outputs/'

## SCREENSHOT FOLDER PATH -> SAVE SCREENSHOT IMAGES
SCREENSHOTS_PATH = './screenshots/'

## AUTOINCREMENTAL NUMBER FILE PATH
AUTOINCREMENTAL_PATH = './components/autoincremental_value.txt'


## DEPENDENCIES !!! DO NOT MODIFY IN ANY CASE !!!
actions = []
settings = {
    'fixed_pause': 1,
    'telegram_notifier': None,
}
running = True
